sections:
  - id: server
    hyperlink: server
    title: Server
    required: true
    description: >
      Configurations required for deploying and identifying a WSO2 Identity Server node.

    configs:
      - key: hostname
        toml_path: server.hostname
        type: string
        required: true
        default: localhost
        possible_values: ["localhost", "identity.example.com"]
        description: >
          The hostname of the machine hosting the Identity Server instance.

      - key: node_ip
        toml_path: server.node_ip
        type: string
        required: true
        default: 127.0.0.1
        possible_values: ["127.0.0.1"]
        description: >
          The IP address of the machine hosting the Identity Server instance.
      
      - key: database
        toml_path: server.database
        type: string
        required: false
        default: localhost
        possible_values: ["localhost", "identity.example.com"]
        description: >
          The database of the machine hosting the Identity Server instance.
  
  - id: keystore.primary
    hyperlink: primary-keystore
    title: Primary keystore
    required: true
    description: >
      Configurations related to the primary keystore.

    configs:
      - key: name
        toml_path: keystore.hostname
        type: string
        required: true
        default: localhost
        possible_values: ["localhost", "identity.example.com"]
        description: >
          The hostname of the machine hosting the Identity Server instance.

      - key: password
        toml_path: keystore.node_ip
        type: string
        required: false
        default: wso2carbon
        possible_values: ["127.0.0.1"]
        description: >
          The password of the keystore file

  
  

